spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: password123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 10000
      connection-timeout: 10000
      max-lifetime: 120000
  threads:
    virtual:
      enabled: true
server:
  error:
    include-stacktrace: never
    include-message: always